name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag my-image-name:latest

      - name: Check Docker image
        run: |
          docker images

      - name: Run Docker container
        run: |
          docker run -d \
            -p 4000:4000 \
            --name container \
            my-image-name:latest

      - name: Check container status
        run: |
          docker ps
          docker ps -a

      - name: Check container logs
        run: |
          docker logs container

      - name: Wait for application
        run: |
          sleep 10

      - name: Test application
        run: |
          curl -v http://localhost:4000
