name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: checking if build is complete
      run: echo "build is complete"
    - name: running the Docker image
      run: docker run -d -p 3000:3000 --name conatiner my-image-name:latest
    - name: checking if push is complete
      run: echo "push is complete"    
    - name: testing the docker container
      run: curl http://localhost:3000  
